version: '3.8'

services:
  db:
    image: postgres:15
    container_name: medikall-postgres
    restart: always
    environment:
      POSTGRES_USER: manager
      POSTGRES_PASSWORD: manager
      POSTGRES_DB: medikall
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - medikall-network

volumes:
  postgres_data:

networks:
  medikall-network:
    external: true
