version: '3.8'

services:
  api_gateway:
    build:
      context: .
    container_name: medikall-api-gateway
    restart: always
    ports:
      - "8000:8000"
    environment:
      MICRO_SERVICE_NAME: API Gateway
      MEDICAL_STAFF_URL: http://medical_staff:8001
      PATIENTS_URL: http://patients:8002
      
      # Keycloak Config
      KEYCLOAK_SERVER_URL: http://keycloak:8080
      KEYCLOAK_REALM: medikall
      KEYCLOAK_CLIENT_ID: api-gateway
      KEYCLOAK_CLIENT_SECRET: GUbaVtOc3CaN1lC4ujZ5KBdHzMDRZLDH

      # JWT Config
      JWT_SECRET_KEY: PR0T0N3C24
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 120    
    networks:
      - medikall-network

networks:
  medikall-network:
    external: true
