services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: medikall-rabbitmq
    ports:
      - "5672:5672"     # Puerto AMQP para apps
      - "15672:15672"   # Interfaz web de administración
    environment:
      RABBITMQ_DEFAULT_USER: manager
      RABBITMQ_DEFAULT_PASS: manager
    networks:
      - medikall-network

networks:
  medikall-network:
    external: true