"""Initial patients migration

Revision ID: 2cd7cfb67ffe
Revises: 
Create Date: 2025-05-22 23:31:46.384423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2cd7cfb67ffe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name_complete', sa.String(length=200), nullable=False),
    sa.Column('medical_staff_id', sa.String(length=40), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='patient_schema'
    )
    op.create_table('logs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('date_create', sa.DateTime(timezone=True), nullable=False),
    sa.Column('patient_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_schema.patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='patient_schema'
    )   
    # ### end Alembic commands ###


def downgrade() -> None:    
    op.drop_table('logs', schema='patient_schema')
    op.drop_table('patients', schema='patient_schema')
    # ### end Alembic commands ###
