"""Initial medical_staff migration

Revision ID: b5ad9a1d0ae4
Revises: 
Create Date: 2025-05-12 02:27:47.344279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5ad9a1d0ae4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_staff',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name_complete', sa.String(length=200), nullable=False),
    sa.Column('specialty', sa.String(length=200), nullable=False),
    sa.Column('license_number', sa.String(length=200), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number'),
    schema='medical_staff_schema'
    )
    op.create_table('shifts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('staff_id', sa.String(length=40), nullable=True),
    sa.Column('shift_date', sa.Date(), nullable=True),
    sa.Column('shift_type', sa.String(length=200), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['medical_staff_schema.medical_staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='medical_staff_schema'
    )
    op.create_table('logs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('date_create', sa.DateTime(timezone=True), nullable=False),
    sa.Column('staff_id', sa.String(length=40), nullable=True),
    sa.Column('shift_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['medical_staff_schema.shifts.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['medical_staff_schema.medical_staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='medical_staff_schema'
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs', schema='medical_staff_schema')
    op.drop_table('shifts', schema='medical_staff_schema')
    op.drop_table('medical_staff', schema='medical_staff_schema')    
    
    # ### end Alembic commands ###
