version: "3.9"

services:
  medical_staff:
    build: .
    container_name: medical_staff
    restart: always
    ports:
      - "8001:8001"
    environment:
      MICRO_SERVICE_NAME: "Medical staff"
      DB_HOST: medikall-postgres
      DB_PORT: 5432
      DB_DATABASE: medikall
      DB_USER: manager
      DB_PASSWORD: manager
      DB_SCHEMA: medical_staff_schema
      DB_SECRET_KEY: 5EPR0T0N3C24
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 120
      JWT_SECRET_KEY: PR0T0N3C24
    networks:
      - medikall-network

networks:
  medikall-network:
    external: true
